apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-add-pod-security
spec:
  rules:
    - name: add-security-context
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            securityContext:
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
