apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod-missing-limits
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"  # Missing cpu limits
