apiVersion: v1
kind: Pod
metadata:
  name: auto-pod-security
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0  # You can specify a trusted version or any valid image
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
