apiVersion: v1
kind: Pod
metadata:
  name: valid-pod-with-tag
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0  # Versioned tag, instead of latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
