apiVersion: v1
kind: Pod
metadata:
  name: valid-pod-with-trusted-image
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0  # A trusted image
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
