apiVersion: v1
kind: Service
metadata:
  name: kyverno-nodeport
  namespace: kyverno
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kyverno
  ports:
    - name: https
      port: 443
      targetPort: 9443
      nodePort: 30443
    - name: metrics
      port: 8000
      targetPort: 8000
      nodePort: 30080
