apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: verify-container-images
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: verify-image-signature
      match:
        resources:
          kinds:
            - Pod
            - Deployment
      verifyImages:
        - imageReferences:
            - "ghcr.io/mycompany/*"
          attestors:
            - entries:
                - keys:
                    publicKeys: |
                      -----BEGIN PUBLIC KEY-----
                      YOUR-PUBLIC-KEY-HERE
                      -----END PUBLIC KEY-----
