apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-requests-limits
  annotations:
    policies.kyverno.io/title: Require Requests and Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers without resource requests and limits can burst and starve other pods.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-for-requests-and-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        resources:
          namespaces:
            - monitoring
            - argocd
      validate:
        message: "Policy Violation: container resources requests and limits are required!"
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
    - name: prod-strict-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - prod
      exclude:
        resources:
          namespaces:
            - monitoring
            - argocd
      validate:
        message: "Production requires stricter limits."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: ">=64Mi"
                    cpu: ">=250m"
                  limits:
                    memory: ">=128Mi"
                    cpu: ">=500m"
    - name: dev-staging-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - dev
                - staging
      exclude:
        resources:
          namespaces:
            - monitoring
            - argocd
      validate:
        message: "Dev/Staging require basic limits."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"