apiVersion: argoprOAoj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd  # Ensure Argo CD is installed in this namespace
spec:
  project: default
  source:
    repoURL: https://github.com/venky2350/Enforce-kubernetes-security-with-kyverno.git
    targetRevision: main  # Branch name
    path: "Project"  # Directory inside the repo where manifests are stored
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true  # Remove resources not in Git
      selfHeal: true  # Sync changes automatically
    syncOptions:
      - CreateNamespace=true  # Automatically create namespace if not present
    